"""empty message

Revision ID: 056192e74bdd
Revises: 976612d45a10
Create Date: 2017-06-11 11:58:32.501324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056192e74bdd'
down_revision = '976612d45a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('postcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'postcode')
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###
