"""empty message

Revision ID: 976612d45a10
Revises: 7e49e1ea8030
Create Date: 2017-06-11 10:51:06.936982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976612d45a10'
down_revision = '7e49e1ea8030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workitems')
    # ### end Alembic commands ###
